### ISSUE TITLE
Capture of deleted names in drop downs

### ISSUE THREAD

**Issue by gaijingal** [clirdlf/digitization_cost_calculator#15]
The drop downs to assign a person to a task are capturing deleted names. If, for example, you go People Performing work and you name salaried person #1 "bob", but then change the name to "Bob," both "bob" and "Bob" appear in the drop down for all the person assignments next to tasks, even though Bob is the only current name in the list above.

**Comment by waynegraham** [comment]
closed in 705853409d6aa7ef694548c1a621f5120249d267
