### ISSUE TITLE
Confirm integration of v cradle scanner

### ISSUE THREAD

**Issue by chrissyrissmeyer** [clirdlf/digitization_cost_calculator#20]
We now have scanning data for an additional image capture device (v cradle scanner) available. Will the new device automatically appear in the calculator when the data is refreshed? Or does this require changes to the code?

V-Cradle scanning time data is located in column AY of the LIVE DATA spreadsheet.

![screen shot 2017-09-29 at 2 19 45 pm](https://user-images.githubusercontent.com/4228849/31036502-567b443a-a521-11e7-80ca-8bc2a1a497c7.png)

**Comment by waynegraham** [comment]
This is in the dropdown list.

The big issue here is that there were two ways that this is listed in the source data:

```
V-Cradle scanner
V-Cradle scanner (i.e., ATIZ BookDrive Pro, Book2Net Cobra)
```

This results in two V-Cradle options in the dropdown. To fix this, the ones that are listed as `V-Cradle scanner` need to be updated to `V-Cradle scanner (i.e., ATIZ BookDrive Pro, Book2Net Cobra)` by someone with write access to the spreadsheet

**Comment by gaijingal** [comment]
I've just corrected it. They are all the second one now.
