### ISSUE TITLE
Error with drop down values in Cost Calculator scanning devices

### ISSUE THREAD

**Issue by chrissyrissmeyer** [clirdlf/digitization_cost_calculator#28]
There is a value showing up in the drop down list of scanning devices that isn't supposed to be there. "Film or transparency scanner (e.g.,...)" is correctly listed as a device type, but then there is an incorrect item in the device list that says  "Image capture-Film or transparency scanner (e.g.,...)-Minutes per 100 scans"

Joyce found the incorrect value in the raw data and corrected it just now. @waynegraham: will it automatically correct itself in the calculator or does something need to be refreshed? She is hoping to get it to disappear before our user testing begins next Monday. 

![screen shot 2018-07-20 at 1 54 01 pm](https://user-images.githubusercontent.com/4228849/43024896-978b0aba-8c24-11e8-9e76-b95591589e9c.png)

**Comment by waynegraham** [comment]
@chrissyrissmeyer This should be fixed by running the default `rake` task to read the spreadsheet and generate the json data.

**Comment by chrissyrissmeyer** [comment]
@waynegraham Thank you! (Is this something I should have done myself?)

**Comment by waynegraham** [comment]
Everyone on the project can run the rebuild. If you’d like to test out the install instructions, we can see if they work!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
