### ISSUE TITLE
Update Contact Us information

### ISSUE THREAD

**Issue by chrissyrissmeyer** [clirdlf/digitization_cost_calculator#29]
Currently, on the [About page](http://dashboard.diglib.org/about/), Joyce's Duke email address is included as the contact. As Joyce has indicated that she is planning to rotate out of the leadership of the group, we should update this. @waynegraham Does CLIR / DLF have an opinion about this?

**Comment by waynegraham** [comment]
You can have have anything on this page that makes sense to the group.

**Comment by chrissyrissmeyer** [comment]
Wayne is going to talk to DLF/CLIR about whether we can include either the dlfaig@clir.org or other clir.org email address here. If we cannot, then the group should talk about what email address makes the most sense here? Maybe create a calculator administrators google group?

**Comment by chrissyrissmeyer** [comment]
@waynegraham: Any updates on whether or not it would be possible to use a clir provided email address (distributed to the group facilitators) on the calculator?

**Comment by waynegraham** [comment]
Let's set this up as a list unless @kimnkl has another way she'd like to handle this.
